name: Sync All Branches



jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Add upstream remote
      run: git remote add upstream https://github.com/organization/micro-servicea/backend.git

    - name: Fetch all branches from upstream
      run: git fetch upstream

    - name: Push updates to fork
      run: |
        git push --all
